# Generated by Django 3.2 on 2023-05-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230509_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='alias',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
