# Generated by Django 3.2 on 2023-09-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('ps', 'Paystack'), ('w', 'Wallet')], default='ps', max_length=3),
        ),
    ]
